version: "3.8"
services:
  nodejs:
    container_name: nodejs
    build: ./nodejs
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=test
    volumes:
      - archery:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -ptest"]
      timeout: 1s
      interval: 3s
      retries: 10
volumes:
  archery:
    external: true
